apiVersion: iam.kubesphere.io/v1beta1
kind: User
metadata:
  annotations:
    iam.kubesphere.io/globalrole: ""
    iam.kubesphere.io/identity-provider.cas: "13508480425"
    iam.kubesphere.io/last-password-change-time: "2022-03-17T08:13:56Z"
    identity-syncer.kubesphere.io/sync-time: "2026-02-03T09:14:09+08:00"
    kubesphere.io/alias-name: E1000035963
    kubesphere.io/description: 运行质量支持团队
  creationTimestamp: "2026-03-05T01:45:13Z"
  name: zouxian
spec:
  email: zouxiands@chinamobile.com
  password: $2a$10$LFJB/jN9/s0f5BZQ30C0Guhp3obmN0zFZBE5ftyVmJy93V5Jf27pC
status:
  lastTransitionTime: "2026-02-03T09:13:35Z"
  state: Active
